name: Build

on:
  push:
    branches-ignore:
      - 'site'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  GO_VERSION: 1.16
  JAVA_VERSION: 11

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-t-${{ hashFiles('hack/make-rules/tools.mk') }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-t-${{ hashFiles('hack/make-rules/tools.mk') }}-go
    - name: Verify
      run: make verify

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-t-${{ hashFiles('hack/make-rules/tools.mk') }}-m2-${{ hashFiles('**/pom.xml') }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-t-${{ hashFiles('hack/make-rules/tools.mk') }}-go
    - name: Test
      run: make test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: fybrik-system
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-t-${{ hashFiles('hack/make-rules/tools.mk') }}-m2-${{ hashFiles('**/pom.xml') }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-t-${{ hashFiles('hack/make-rules/tools.mk') }}-go
    - name: Install tools
      run: make install-tools
    - name: Integration tests
      run: make run-integration-tests
    - run: docker images
    - name: Save images
      if: ${{ github.event_name != 'pull_request' }}
      run: make save-images
    - name: Upload images
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: images.tar
        retention-days: 1

  push_images:
    name: Push images
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: fybrik-system
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    needs: [verify, test, integration-tests]
    if: ${{ github.event_name != 'pull_request' && github.repository == 'fybrik/data-movement-operator' }}
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/download-artifact@v2
      with:
        name: images
    - name: Load images
      if: ${{ github.event_name != 'pull_request' }}
      run: docker load -i images.tar
    - run: docker images
    - id: version
      name: Infer version
      run: |
        echo "DOCKER_PUBLIC_TAGNAME=latest" >> $GITHUB_ENV
        echo "HELM_PUBLIC_TAGNAME=0.0.0" >> $GITHUB_ENV
        if: ${{ (github.event_name != 'pull_request') && contains(github.ref, 'tags') }}
        run: |
          echo "HELM_PUBLIC_TAGNAME=${GITHUB_REF##*/v}" >> $GITHUB_ENV
          echo "DOCKER_PUBLIC_TAGNAME=${GITHUB_REF##*/v}" >> $GITHUB_ENV
    - name: Helm chart push
      if: ${{ (github.event_name != 'pull_request') }}
      run: |
        export HELM_EXPERIMENTAL_OCI=1
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u "${{ github.actor }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
        make docker-retag-and-push-public && make helm-push-public
